### ISSUE TITLE
Scoreboard showing "Unknown Player"

### ISSUE THREAD

**Issue by Mangrogred** [sousou63/DarkRP-old#162]
I was just playing dark rp and when everyone left the q menu was broken
![изображение](https://github.com/user-attachments/assets/4bfbc8aa-874a-476e-af96-3cb1fb5a367a)

**Comment by QueenPM** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at LeaderBoard.GetJobNameForUser(PlayerConnObject p) in UI/LeaderBoard.razor:line 39
   at LeaderBoard.BuildRenderTree(RenderTreeBuilder __builder) in UI/LeaderBoard.razor:line 22
   at Sandbox.<PanelComponent>FA1C5275512F4A92FD662E1A2B690E382292D174E8B798CBA2E5730251CFA55D7__CustomBuildPanel.BuildRenderTree(RenderTreeBuilder v) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\UI\PanelComponent.cs:line 195
   at Sandbox.UI.Panel.InternalRenderTree() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\UI2\Panel\Panel.Razor.cs:line 95
   ```

**Comment by ghost** [comment]
Probably fixed in #177

**Comment by SebbeJohansson** [comment]
@dimmerly Cant verify that.
